config/routes.rb
Rails.application.routes.draw do
  root to: 'websites#index'
  get 'gradient_maker', to: 'websites#gradient_maker'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/website.rb
class Website < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def index
    @websites = Website.all
  end

  def gradient_maker

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_default_iframe.html.erb
<div class="h-100 w-100 bg-light">

</div>

app/views/websites/gradient_maker.html.erb
<%= turbo_frame_tag :projects do %>
<div data-controller="gradient-maker" data-gradient-maker-target="background" class="h-100">
  <!-- color wheel -->
  <div class="d-flex flex-column align-items-center justify-content-between border rounded-2 position-absolute  py-1 pxw-200 pxh-200 bg-dark-blue-a d-none" data-gradient-maker-target="color_wheel_container">
    <div class="d-flex flex-column gap-2 align-items-center">
      <div class="d-flex gap-4 align-items-center">
        <p class="mx-4 text-white"></p>
        <p class="pt-1 text-white m-0" data-gradient-maker-target="color_wheel_label">######</p>
        <button class="pxh-20 pxw-50 bg-danger rounded-pill center-text text-white border-0 " data-action="click->gradient-maker#remove_color click->gradient-maker#display_gradient"><span>del</span></button>
      </div>
      <input class="pxw-180" type="color" data-gradient-maker-target="color_input"/>
      <input class="pxw-180" type="range" min="1" max="360" data-gradient-maker-target="range_input" data-action="click->gradient-maker#displayDeg"/>
      <p class="text-white" data-gradient-maker-target="deg_display">180deg</p>
    </div>
    <button class="rounded-pill border-0 bg-success" data-action="click->gradient-maker#Pick_color_val click->gradient-maker#display_gradient">enter</button>
  </div>
  <!-- end color wheel -->


  <!-- color container -->
  <div class="container bg-dark-blue-a rounded-2 border py-4 lg-vw-45 md-vw-65 position-relative t-45"  >
      <div class="row px-5 overflow-y max-pxh-90" data-gradient-maker-target="colors">
        <!--colors gened here-->

      </div>
      <button class="col-1 rounded-pill pxw-100 pxh-40 center-text p-0 border-0 position-absolute" data-action="click->gradient-maker#add_color"><span>add color</span></button>

    <div class="mx-auto bg-white border px-1 py-2 w-50 overflow-y max-pxh-60" data-gradient-maker-target="color_css">
      text
    </div>

  </div>
  <!-- end color container -->


</div>
<% end %>

app/views/websites/index.html.erb
<div class="d-flex justify-content-between border bg-secondary py-4">
  <h3 class="ps-2">portfolio page</h3>
  <span class="pe-4">
    <a class="btn border">link</a>
    <a class="btn border">link</a>
    <a class="btn border">link</a>
  </span>
</div>

<div class="row" data-controller="websites" >
  <div class="border col-2 list-group list-group-flush p-0 overflow-y">
    <%= link_to "gradient_maker", gradient_maker_path,
     class: "list-group-item list-group-item-action" ,
    data: {turbo_frame: :projects}%>
    <!-- websites url list -->
    <% @websites.each do |website| %>
      <a class="list-group-item list-group-item-action" data-url="<%= website.url %>" data-action="click->websites#show_website"><%= website.name %></a>
    <% end %>
  </div>
  <div class="col-9 p-4 ms-5 ">
    <div class="container border vh-80 p-0">
      <%= turbo_frame_tag :projects do %>

      <% end %>
    </div>
  </div>
</div>